# Generated by Django 3.2.5 on 2021-07-03 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_auto_20210701_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('posted_on', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art.category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art.location')),
            ],
        ),
    ]
